name: Docker

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  # TODO: disabled for now because it takes too long in CI
  # pull_request:
  #   branches:
  #     - main
  #   paths:
  #     - 'Makefile'
  #     - 'pyproject.toml'
  #     - 'src/olmo_core/version.py'
  #     - 'src/Dockerfile'
  #     - '.github/workflows/docker.yml'
  push:
    # branches:
    #   - main
    tags:
      - 'v*.*.*'

jobs:
  beaker:
    name: Beaker images
    runs-on: ubuntu-latest-m
    timeout-minutes: 60
    env:
      BEAKER_TOKEN: ${{ secrets.BEAKER_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set env vars
        run: |
          echo "BEAKER_WORKSPACE=$(make get-beaker-workspace)" >> $GITHUB_ENV
          rm -rf /opt/hostedtoolcache  # clear up some disk space

      - name: Build stable image
        run: |
          make stable-image

      - name: Build nightly image
        run: |
          make nightly-image

      - name: Authenticate with GHCR
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Authenticate with Beaker
        uses: allenai/setup-beaker@v2
        if: env.BEAKER_TOKEN != ''
        with:
          token: ${{ env.BEAKER_TOKEN }}
          workspace: ${{ env.BEAKER_WORKSPACE }}

      - name: Push stable image to GHCR
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          make ghcr-image-stable

      - name: Push nightly image to GHCR
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          make ghcr-image-nightly

      - name: Push stable image to Beaker
        if: env.BEAKER_TOKEN != '' && startsWith(github.ref, 'refs/tags/')
        run: |
          make beaker-image-stable

      - name: Push nightly image to Beaker
        if: env.BEAKER_TOKEN != '' && startsWith(github.ref, 'refs/tags/')
        run: |
          make beaker-image-nightly
